# Generated by Django 3.0.7 on 2020-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0033_auto_20200825_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not', 'Не обработан'), ('in', 'В обработке'), ('com', 'Выполнен'), ('rej', 'Отменен')], default='not', max_length=3),
        ),
    ]
